#!/bin/sh

#getting the init
get_init() {
    os="$(uname -o)"
    case "$os" in
        Android)
            echo "init.rc"
            ;;
        *)
            if [ -f "/sbin/openrc" ]; then
                echo "openrc"
            elif [ -e "/proc/1/comm" ]; then
                awk '{print $1}' /proc/1/comm
            else
                echo "unknown"
            fi
            ;;
    esac
}

# Read hostname
host=$(cat /proc/sys/kernel/hostname)

# Detect OS information
for os in /etc/os-release /usr/lib/os-release; do
    if [ -f "$os" ]; then
        . "$os"
        break
    fi
done

# Get CPU model
CPU=$(awk -F: '/model name/ { print $2; exit }' /proc/cpuinfo | sed 's/ @/\n/' | head -1 | sed 's/ //')

# Get Kernel version
KERNEL=$(uname -srm)

# Detect window manager
if [ -z "${WM}" ]; then
    if [ -n "${XDG_CURRENT_DESKTOP}" ]; then
        WM="${XDG_CURRENT_DESKTOP}"
    elif [ -n "${DESKTOP_SESSION}" ]; then
        WM="${DESKTOP_SESSION}"
    else
        WM=$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)
    fi
fi

# Get shell name
SHELL=$(basename "$SHELL")

# Get kernel version
kernel=$(uname -r)

# Define colors
bc=$(tput bold)       # bold
c0=$(tput setaf 0)    # black
c1=$(tput setaf 1)    # red
c2=$(tput setaf 2)    # green
c3=$(tput setaf 3)    # yellow
c4=$(tput setaf 4)    # blue
c5=$(tput setaf 5)    # magenta
c6=$(tput setaf 6)    # cyan
c7=$(tput setaf 7)    # white
rc=$(tput sgr0)      # reset

# Colors for labels
lc="${bc}${c6}"      # labels
nc="${bc}${c6}"      # user and hostname
tc="${bc}${c7}"      # text
fc="${bc}${c6}"      # first color
sc="${c6}"          # second color

# Output results
cat << EOF
        ${lc}wm ~ ${rc}${lc}${WM}${rc}
        ${lc}os ~ ${rc}${tc}${PRETTY_NAME}${rc}
        ${lc}sh ~ ${rc}${tc}${SHELL}${rc}
        ${lc}sv ~ ${rc}${tc}$(get_init)${rc}
        ${lc}kr ~ ${rc}${tc}${kernel}${rc}
EOF
